# Generated by Django 2.2.12 on 2021-01-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='品牌名称')),
                ('product_img', models.ImageField(null=True, upload_to='avatar', verbose_name='种类名称')),
                ('img', models.ImageField(null=True, upload_to='avatar', verbose_name='轮播图图片')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('description', models.CharField(max_length=30, verbose_name='商品描述')),
                ('original_price', models.FloatField(verbose_name='原价')),
                ('price', models.FloatField(verbose_name='售价')),
                ('amount', models.IntegerField(verbose_name='购买数量')),
                ('quantity', models.IntegerField(verbose_name='库存')),
                ('sales_volumes', models.IntegerField(verbose_name='销量')),
                ('status', models.CharField(default='O', max_length=30, verbose_name='状态')),
                ('type', models.CharField(default='轻薄笔记本', max_length=30, verbose_name='笔记本类型')),
                ('GPU_brand', models.CharField(max_length=30, verbose_name='显卡品牌')),
                ('GPU_type', models.CharField(max_length=30, verbose_name='显卡类型')),
                ('CPU_brand', models.CharField(max_length=30, verbose_name='处理器品牌')),
                ('CPU_type', models.CharField(max_length=30, verbose_name='处理器类型')),
                ('RAM', models.CharField(max_length=30, verbose_name='内存大小')),
                ('hard_disk', models.CharField(max_length=30, verbose_name='硬盘大小')),
                ('size', models.CharField(max_length=30, verbose_name='电脑尺寸')),
                ('resolution_ratio', models.CharField(max_length=30, verbose_name='屏幕分辨率')),
                ('operating_system', models.CharField(max_length=30, verbose_name='电脑操作系统')),
                ('weight', models.CharField(max_length=30, verbose_name='重量')),
                ('color', models.CharField(max_length=30, verbose_name='颜色')),
                ('product_from', models.CharField(max_length=30, verbose_name='产地')),
                ('purpose', models.CharField(max_length=30, verbose_name='用途')),
                ('level', models.CharField(max_length=30, verbose_name='档次')),
                ('group', models.CharField(max_length=30, verbose_name='用户群体')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.Image')),
            ],
        ),
    ]
