# Generated by Django 2.2.12 on 2021-01-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commodity',
            table='commodity',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
